#!/bin/bash
USE_MWU=0
ARGS=""
# Parse arguments
for arg in "$@"; do
  if [ "$arg" = "-mwu" ]; then
    USE_MWU=1
  else
    ARGS="$ARGS $arg"
  fi
done

# Set local directory paths
BIN_DIR="./treetagger/bin"
CMD_DIR="./treetagger/cmd"
LIB_DIR="./treetagger/lib"

# The Pipeline
if [ "$USE_MWU" -eq 1 ]; then
  # Full Pipeline with Multi-Word Units
  "$CMD_DIR/utf8-tokenize.perl" -a "$LIB_DIR/indonesian-abbreviations" $ARGS | \
  perl "$CMD_DIR/split-clitics.perl" | \
  perl "$CMD_DIR/mwl-lookup.perl" -f "$LIB_DIR/indonesian-mwls.txt" | \
  "$BIN_DIR/tree-tagger" "$LIB_DIR/indonesian.par" -token -lemma | \
  perl "$CMD_DIR/morph-fixer.perl"
else
  # Standard Pipeline
  "$CMD_DIR/utf8-tokenize.perl" -a "$LIB_DIR/indonesian-abbreviations" $ARGS | \
  perl "$CMD_DIR/split-clitics.perl" | \
  "$BIN_DIR/tree-tagger" "$LIB_DIR/indonesian.par" -token -lemma | \
  perl "$CMD_DIR/morph-fixer.perl"
fi
